stages:
  - build
  - push
  - deploy
  - cleanup

build_staging_backend:
  stage: build
  only:
    - master
  script:
    - docker build -t registry.axiom/atp-server:latest -f Dockerfile.backend .

build_staging_frontend:
  stage: build
  only:
    - master
  script:
    - docker build -t registry.axiom/atp-site:latest --build-arg MAPBOX_TOKEN=$MAPBOX_TOKEN --build-arg DATA_URL=https://stage-atn-server.srv.axds.co .

push_staging_backend:
  stage: push
  only:
    - master
  script:
    - docker push registry.axiom/atp-server:latest

push_staging_frontend:
  stage: push
  only:
    - master
  script:
    - docker push registry.axiom/atp-site:latest

deploy_staging_backend:
  stage: deploy
  environment:
    name: stage
    url: http://stage-atp-server.srv.axds.co
    on_stop: stop_staging_backend
  only:
    - master
  script:
    - docker pull registry.axiom/ansible
    - docker run --rm registry.axiom/ansible ap apps-stage atp-server --tags deploy

deploy_staging_frontend:
  stage: deploy
  environment:
    name: stage-frontend
    url: http://stage-atp-site.srv.axds.co
    on_stop: stop_staging_frontend
  only:
    - master
  script:
    - docker pull registry.axiom/ansible
    - docker run --rm registry.axiom/ansible ap apps-stage atp-site --tags deploy

stop_staging_backend:
  stage: deploy
  only:
    - master
  when: manual
  environment:
    name: stage
    action: stop
  script:
    - docker pull registry.axiom/ansible
    - docker run --rm registry.axiom/ansible ap apps-stage atp-server --tags deploy -e atp_server_state=stopped

stop_staging_frontend:
  stage: deploy
  only:
    - master
  when: manual
  environment:
    name: stage-frontend
    action: stop
  script:
    - docker pull registry.axiom/ansible
    - docker run --rm registry.axiom/ansible ap apps-stage atp-site --tags deploy -e atp_site_state=stopped

cleanup_staging_backend:
  stage: cleanup
  only:
    - master
  script:
    - docker rmi --no-prune registry.axiom/atp-server:latest

cleanup_staging_frontend:
  stage: cleanup
  only:
    - master
  script:
    - docker rmi --no-prune registry.axiom/atp-site:latest
