stages:
  - build
  - push
  - deploy
  - cleanup

build_staging_backend:
  stage: build
  only:
    - master
  script:
    - docker build -t registry.axiom/atp-server:latest -f Dockerfile.backend .

build_staging_frontend:
  stage: build
  only:
    - master
  script:
    - docker build -t registry.axiom/atp-frontend:latest --build-arg MAPBOX_TOKEN=$MAPBOX_TOKEN --build-arg DATA_URL=$DATA_URL .

push_staging_backend:
  stage: push
  only:
    - master
  script:
    - docker push registry.axiom/atp-server:latest

push_staging_frontend:
  stage: push
  only:
    - master
  script:
    - docker push registry.axiom/atp-frontend:latest

deploy_staging_backend:
  stage: deploy
  environment:
    name: stage
    url: http://stage-atp-server.srv.axds.co
    on_stop: stop_staging_backend
  only:
    - master
  script:
    - docker run --rm registry.axiom/ansible ap apps-stage atp-server --tags deploy

stop_staging_backend:
  stage: deploy
  only:
    - master
  when: manual
  environment:
    name: stage
    action: stop
  script:
    - docker run --rm registry.axiom/ansible ap apps-stage atp-server --tags deploy -e atp_server_state=stopped

cleanup_staging_backend:
  stage: cleanup
  only:
    - master
  script:
    - docker rmi --no-prune registry.axiom/atp-server:latest
