stages:
  - cidebug
  - build
  - push
  - deploy
  - cleanup

debug_ci:
  stage: cidebug
  script:
    - sleep infinity

build_staging_backend:
  stage: build
  only:
    - master
    - branches
  script:
    - docker build -t registry.axiom/atp-server:latest -f Dockerfile.backend .

build_staging_frontend:
  stage: build
  only:
    - master
    - branches
  script:
    - docker build -t registry.axiom/atp-site:latest --build-arg MAPBOX_TOKEN=$MAPBOX_TOKEN --build-arg DATA_URL=https://stage-atp-server.srv.axds.co .

build_production_backend:
  stage: build
  only:
    - tags
  script:
    - docker build -t registry.axiom/atp-server:$CI_COMMIT_REF_NAME -f Dockerfile.backend .
    - docker tag registry.axiom/atp-server:$CI_COMMIT_REF_NAME registry.axiom/atp-server:prod

build_production_frontend:
  stage: build
  only:
    refs:
      - tags
      - testpipe
    changes:
      - static/*
      - src/*
      - src/**/*
      - package.json
      - yarn.lock
      - .babelrc
      - .postcssrc
      - tailwind.config.js
      - .gitlab-ci.yml
  variables:
    MAPBOX_TOKEN: '$MAPBOX_TOKEN'
    DATA_URL: 'https://atp-server.srv.axds.co'
  image: node:12
  script:
    - yarn install --production=false
    - export DATA_URL='https://atp-server.srv.axds.co'
    - env
    - yarn run build-prod
  artifacts:
    paths:
      - dist/prod/content.html
      - dist/prod/footer.html

push_staging_backend:
  stage: push
  only:
    - master
  script:
    - docker push registry.axiom/atp-server:latest

push_staging_frontend:
  stage: push
  only:
    - master
  script:
    - docker push registry.axiom/atp-site:latest

push_production_backend:
  stage: push
  only:
    - tags
  script:
    - docker push registry.axiom/atp-server:$CI_COMMIT_REF_NAME
    - docker push registry.axiom/atp-server:prod

deploy_staging_backend:
  stage: deploy
  environment:
    name: stage
    url: http://stage-atp-server.srv.axds.co
    on_stop: stop_staging_backend
  only:
    - master
  tags:
    - aps
  script:
    - aps apps-stage atp-server

deploy_staging_frontend:
  stage: deploy
  environment:
    name: stage-frontend
    url: http://stage-atp-site.srv.axds.co
    on_stop: stop_staging_frontend
  only:
    - master
  tags:
    - aps
  script:
    - aps apps-stage atp-site

deploy_production_backend:
  stage: deploy
  environment:
    name: prod
    url: http://atp-server.srv.axds.co
  only:
    - tags
  tags:
    - aps
  script:
    - aps apps-prod atp-server -e atp_server_version=$CI_COMMIT_REF_NAME

deploy_production_frontend:
  stage: deploy
  only:
    refs:
      - tags
      - testpipe
    changes:
      - static/*
      - src/*
      - src/**/*
      - package.json
      - yarn.lock
      - .babelrc
      - .postcssrc
      - tailwind.config.js
      - .gitlab-ci.yml
  environment:
    name: prod-frontend
    url: https://secoora.org/fact/data-visualization-tool/
  tags:
    - aps
  script:
    - aps external atp-site-prod -e atp_site_local_artifact_path=$CI_BUILDS_DIR/$CI_PROJECT_PATH/dist/prod

stop_staging_backend:
  stage: deploy
  only:
    - master
  when: manual
  environment:
    name: stage
    action: stop
  tags:
    - aps
  script:
    - aps apps-stage atp-server -e atp_server_state=stopped

stop_staging_frontend:
  stage: deploy
  only:
    - master
  when: manual
  environment:
    name: stage-frontend
    action: stop
  tags:
    - aps
  script:
    - aps apps-stage atp-site -e atp_site_state=stopped

cleanup_staging_backend:
  stage: cleanup
  only:
    - master
  script:
    - docker rmi --no-prune registry.axiom/atp-server:latest

cleanup_staging_frontend:
  stage: cleanup
  only:
    - master
  script:
    - docker rmi --no-prune registry.axiom/atp-site:latest

cleanup_production_backend:
  stage: cleanup
  only:
    - tags
  script:
    - docker rmi --no-prune registry.axiom/atp-server:$CI_COMMIT_REF_NAME
    - docker rmi --no-prune registry.axiom/atp-server:prod
