stages:
  - build
  - push
  - deploy
  - cleanup

build_staging_backend:
  stage: build
  only:
    - master
  script:
    - docker build -t registry.axiom/atp-server:latest -f Dockerfile.backend .

build_staging_frontend:
  stage: build
  only:
    - master
  script:
    - docker build -t registry.axiom/atp-site:latest --build-arg MAPBOX_TOKEN=$MAPBOX_TOKEN --build-arg DATA_URL=https://stage-atp-server.srv.axds.co .

build_production_backend:
  stage: build
  only:
    - tags
  script:
    - docker build -t registry.axiom/atp-server:$CI_COMMIT_REF_NAME -f Dockerfile.backend .
    - docker tag registry.axiom/atp-server:$CI_COMMIT_REF_NAME registry.axiom/atp-server:prod

build_production_frontend:
  stage: build
  only:
    - tags
  script:
    - docker build -t registry.axiom/atp-site:$CI_COMMIT_REF_NAME --build-arg MAPBOX_TOKEN=$MAPBOX_TOKEN --build-arg DATA_URL=https://atp-server.srv.axds.co .
    - docker tag registry.axiom/atp-site:$CI_COMMIT_REF_NAME registry.axiom/atp-site:prod

push_staging_backend:
  stage: push
  only:
    - master
  script:
    - docker push registry.axiom/atp-server:latest

push_staging_frontend:
  stage: push
  only:
    - master
  script:
    - docker push registry.axiom/atp-site:latest

push_production_backend:
  stage: push
  only:
    - tags
  script:
    - docker push registry.axiom/atp-server:$CI_COMMIT_REF_NAME
    - docker push registry.axiom/atp-server:prod

push_production_frontend:
  stage: push
  only:
    - tags
  script:
    - docker push registry.axiom/atp-site:$CI_COMMIT_REF_NAME
    - docker push registry.axiom/atp-site:prod

deploy_staging_backend:
  stage: deploy
  environment:
    name: stage
    url: http://stage-atp-server.srv.axds.co
    on_stop: stop_staging_backend
  only:
    - master
  script:
    - docker pull registry.axiom/ansible
    - docker run --rm registry.axiom/ansible ap apps-stage atp-server --tags deploy

deploy_staging_frontend:
  stage: deploy
  environment:
    name: stage-frontend
    url: http://stage-atp-site.srv.axds.co
    on_stop: stop_staging_frontend
  only:
    - master
  script:
    - docker pull registry.axiom/ansible
    - docker run --rm registry.axiom/ansible ap apps-stage atp-site --tags deploy

deploy_production_backend:
  stage: deploy
  environment:
    name: prod
    url: http://atp-server.srv.axds.co
  only:
    - tags
  script:
    - docker pull registry.axiom/ansible
    - docker run --rm registry.axiom/ansible ap apps-prod atp-server -e atp_server_version=$CI_COMMIT_REF_NAME --tags deploy

deploy_production_frontend:
  stage: deploy
  environment:
    name: prod-frontend
    url: http://atp-site.srv.axds.co
  only:
    - tags
  script:
    - docker pull registry.axiom/ansible
    - docker run --rm registry.axiom/ansible ap apps-prod atp-site -e atp_site_version=$CI_COMMIT_REF_NAME --tags deploy

stop_staging_backend:
  stage: deploy
  only:
    - master
  when: manual
  environment:
    name: stage
    action: stop
  script:
    - docker pull registry.axiom/ansible
    - docker run --rm registry.axiom/ansible ap apps-stage atp-server --tags deploy -e atp_server_state=stopped

stop_staging_frontend:
  stage: deploy
  only:
    - master
  when: manual
  environment:
    name: stage-frontend
    action: stop
  script:
    - docker pull registry.axiom/ansible
    - docker run --rm registry.axiom/ansible ap apps-stage atp-site --tags deploy -e atp_site_state=stopped

cleanup_staging_backend:
  stage: cleanup
  only:
    - master
  script:
    - docker rmi --no-prune registry.axiom/atp-server:latest

cleanup_staging_frontend:
  stage: cleanup
  only:
    - master
  script:
    - docker rmi --no-prune registry.axiom/atp-site:latest

cleanup_production_backend:
  stage: cleanup
  only:
    - tags
  script:
    - docker rmi --no-prune registry.axiom/atp-server:$CI_COMMIT_REF_NAME
    - docker rmi --no-prune registry.axiom/atp-server:prod

cleanup_production_frontend:
  stage: cleanup
  only:
    - tags
  script:
    - docker rmi --no-prune registry.axiom/atp-site:$CI_COMMIT_REF_NAME
    - docker rmi --no-prune registry.axiom/atp-site:prod
